language: java
jdk:
  - oraclejdk8
cache:
  directories:
    - '$HOME/.m2/repository'
script:
  - git clone https://github.com/power-libraries/primitivepower.git dependency
  - cd dependency/primitivepower
  - mvn package install
  - cd ../../arraypower-generator
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - mvn test -Dmaven.javadoc.skip=true -B
  - mvn exec:java -DskipTests=true -Dmaven.javadoc.skip=true -Dexec.args="../tmp/"
  - cd ..
  - diff -qrN tmp/ arraypower/
  - cd arraypower
  - mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V 
  - mvn test -Dmaven.javadoc.skip=true -B
